# Generated by Django 5.1.2 on 2024-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_article_created_at_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
